# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               MrChristine
tagline:             'Where dreams are made of'
description:         'A place to keep my ideas outside of my head'
url:                 http://mrchristine.github.io
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              Miklos Christine
  url:               https://twitter.com/Miklos_C

# Custom vars
version:             1.0.0
