# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Mister Christine
tagline:             'A Lifestyle Like No Other'
description:         'A dumping ground for my thoughts'
url:                 http://mrchristine.github.io
baseurl:             ''
gems:                [jekyll-paginate]
paginate:            5

# About/contact
author:
  name:              Miklos Christine
  url:               https://twitter.com/Miklos_C

# GitHub
github:
  repo:							 http://github.com/mrchristine

# Custom vars
version:             1.0.0
